# Generated by Django 4.1.3 on 2023-09-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='city_of_residence',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='base.ebook'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='year_published',
            field=models.IntegerField(),
        ),
    ]
