# Generated by Django 4.1.3 on 2023-09-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_userprofileinfo_city_of_residence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='year_published',
            field=models.CharField(max_length=64),
        ),
    ]
