# Generated by Django 4.1.3 on 2023-09-10 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_ebook_year_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='country_of_residence',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
