# Generated by Django 4.2.5 on 2023-09-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_userprofileinfo_country_of_residence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='year_published',
            field=models.IntegerField(max_length=64),
        ),
    ]
