# Generated by Django 4.2.5 on 2023-09-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_ebook_year_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='year_published',
            field=models.IntegerField(),
        ),
    ]
